{
 "title": "database_logger dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job_var",
    "query": {}
   },
   {
    "name": "component_var",
    "query": {}
   },
   {
    "name": "stage_var",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Error count per stage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(stage)(count_over_time({job=\"$job_var\", component=\"$component_var\", stage=~\".+\"} |~ \"(?i)error\" [5m]))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Most active stages per component",
   "type": "piechart",
   "description": "logs distribution in pie chart last 5m",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (stage) (count_over_time({job=\"$job_var\", component=\"$component_var\"}[5m])) \r\n"
    }
   ]
  },
  {
   "title": "count of error logs in stagge (5m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=~\"$job_var\", component=~\"$component_var\",stage=~\"$stage_var\"} |~ \"(?i)error\" [5m])\r\n"
    }
   ]
  },
  {
   "title": "Success percentage (BY STAGE)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 * (count_over_time({job=\"$job_var\", component=\"$component_var\", stage=\"$stage_var\", level=\"INFO\"} [$__range]) /\r\ncount_over_time({job=\"$job_var\", component=\"$component_var\", stage=\"$stage_var\"} [$__range]))\r\n"
    }
   ]
  },
  {
   "title": "Logs in Tabular",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 8, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job_var\", component=\"$component_var\"} | json "
    }
   ]
  },
  {
   "title": "logs distribution by level",
   "type": "piechart",
   "description": "logs distribution in pie chart last 5m",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (\r\n  label_replace(count_over_time({job=\"$job_var\", component=\"$component_var\",stage=\"$stage_var\"} |~ \"(?i)INFO\" [5m]), \"level\", \"INFO\", \"\", \"\") or \r\n  label_replace(count_over_time({job=\"$job_var\", component=\"$component_var\",stage=\"$stage_var\"} |~ \"(?i)WARNING\" [5m]), \"level\", \"WARNING\", \"\", \"\") or \r\n  label_replace(count_over_time({job=\"$job_var\", component=\"$component_var\",stage=\"$stage_var\"} |~ \"(?i)ERROR\" [5m]), \"level\", \"ERROR\", \"\", \"\") or\r\n  label_replace(count_over_time({job=\"$job_var\", component=\"$component_var\",stage=\"$stage_var\"} |~ \"(?i)CRITICAL\" [5m]), \"level\", \"CRITICAL\", \"\", \"\")\r\n) by (level, component)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Log Volume by Component (Bar Chart)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=~\"$job_var\"}[5m])) by (component)\r\n"
    }
   ]
  },
  {
   "title": "log volume over 5m",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(stage)(count_over_time({job=\"$job_var\", component=\"$component_var\",stage=~\".+\"}[5m])) or vector(0)\r\n"
    }
   ]
  }
 ]
}