{
 "title": "loki dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job_var",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "logs distribution",
   "type": "piechart",
   "description": "logs distribution in pie chart last 5m",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (\r\n  label_replace(count_over_time({job=\"$job_var\"} |~ \"(?i)INFO\" [5m]), \"level\", \"INFO\", \"\", \"\") or \r\n  label_replace(count_over_time({job=\"$job_var\"} |~ \"(?i)WARNING\" [5m]), \"level\", \"WARNING\", \"\", \"\") or \r\n  label_replace(count_over_time({job=\"$job_var\"} |~ \"(?i)ERROR\" [5m]), \"level\", \"ERROR\", \"\", \"\")\r\n) by (level)\r\n"
    }
   ]
  },
  {
   "title": "Log Volume (Last 5m)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=~\".+\"} [5m])\r\n",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "count of error logs over 5m ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=~\"$job_var\"} |~ \"(?i)error\" [5m])\r\n"
    }
   ]
  },
  {
   "title": "Logs in Tabular",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job_var\"}"
    }
   ]
  },
  {
   "title": "Error Events Across Jobs (5m Window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=~\".+\"} |~ \"(?i)error\" [5m])\r\n"
    }
   ]
  }
 ]
}