version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - D:/DE_personal/docker_personal/logging_dockerfile/loki_data:/loki
    command: -config.file=/etc/loki/local-config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - D:/DE_personal/docker_personal/logging_dockerfile/grafana_data:/var/lib/grafana
      
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Default username
      - GF_SECURITY_ADMIN_PASSWORD=wSnEPGCJys-c$6!  # Set a secure password
    depends_on:
      - loki

  python-logger:
    build: .
    container_name: python_logger
    volumes:
      - ./python_Files:/app
    ports:
      - "8501:8501"  # Expose Streamlit
    depends_on:
      - loki
    restart: always


volumes:
  grafana-storage:
