{
 "title": "Kafka_Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU ,memory and kafka metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100- (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka Broker Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kafka Topic Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=\"chat-messages\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_consumergroup_current_offset",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset"
    }
   ]
  },
  {
   "title": "topic current offset",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"chat-messages\"}"
    }
   ]
  },
  {
   "title": "consumer_lag graph",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=\"chat-messages\"}"
    }
   ]
  }
 ]
}